include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "lib/generated/**"
    - "build/**"
    - "**.freezed.dart"
    - "**.g.dart"
    - "lib/ui/routes/router.gr.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

linter:
  rules:
    public_member_api_docs: false
    prefer_single_quotes: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    avoid_setters_without_getters: false
    library_private_types_in_public_api: false
    use_key_in_widget_constructors: false
    sort_pub_dependencies: false
