name: nant_client
description: Тот самый циганский клиент для тестового задания

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  responsive_framework: <=0.0.15
  cupertino_icons: <=1.2.0
  dio: ">=3.0.0 <4.0.0-beta4"
  get_it: <=6.0.0
  dash_chat:
    git:
      url: git://github.com/diegogarciar/dash_chat.git
  worker_manager: <=3.2.0
  logger: <=0.9.4
  flutter_bloc: <=6.1.1
  freezed_annotation: <=0.12.0
  hive: <=1.6.0-nullsafety.2
  keyboard_dismisser: <=1.0.2
  path_provider: <=1.6.27
  web_socket_channel: <=1.2.0
  pedantic: <=1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: <=1.11.1
  freezed: <=0.14.0
  hive_generator: <=0.9.0-nullsafety.1
  flutter_launcher_icons: <=0.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/flags/

flutter_intl:
  enabled: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/icon.png"